### ISSUE TITLE
What happens if there is no task available?

### ISSUE THREAD

**Issue by eight04** [dd-center/Cluster-center#1]
I also wonder why the client has to pull tasks manually?

**Comment by simon300000** [comment]
The underlying task manager is here https://github.com/simon300000/athome
If there is no task available, the client will be added to pulls waiting list, waiting for incoming task

**Comment by simon300000** [comment]
I want clients to control how much task they want to take, so the client will pull task

**Comment by eight04** [comment]
> the client will be added to pulls waiting list, waiting for incoming task

This causes the client making 48 HTTP requests in a second:

1. The client spawns 48 processors.
2. 48 requests are sent to the server ([separately, with a random delay](https://github.com/dd-center/DDatHome-nodejs/blob/341bbd8a2b7f24012841cec176df13bca8b42eb6/index.js#L80)).
3. 48 requests are added to the waiting list.
4. The server generates 1000 jobs.
5. 48 jobs are sent to the same client at the same time.
6. The client makes 48 HTTP requests in a second.

It should be better if:

1. When sending a message to the server, if there is no task available, the server should respond immediately and tell the client to retry later.
2. When sending a message to the client, if the client has too many tasks, it should respond immediately and tell the server to deliver the task to other clients.

**Comment by simon300000** [comment]
Yes you are right, thanks for you help, this is a better idea

**Comment by simon300000** [comment]
I am thinking of this idea:
When receiving pulls, if the task pending is empty, then wait until there is task available and actually pull it, the good point of this is only requiring modifying the server side

**Comment by eight04** [comment]
But then the client still cannot control when to process the task.

---

We still need a way to report client error so the server can deliver the task to other clients. I saw that [HTTP errors are reported as something like `"{code:<number>}"`](https://github.com/dd-center/DDatHome-nodejs/blob/341bbd8a2b7f24012841cec176df13bca8b42eb6/index.js#L88). Does the server pass the task to other clients in this case?

**Comment by simon300000** [comment]
Yes the task will be pass to other/same client again
https://github.com/dd-center/Cluster-center/blob/4aa27a88a057115013c58b15820226083cf5465d/index.js#L16-L23
I use this function to validate the result, if the return is falsely then the task will be redistributed.

**Comment by simon300000** [comment]
> When sending a message to the server, if there is no task available, the server should respond immediately and tell the client to retry later.

I implemented this idea with a new "protocol" `DDDhttp`, This could be used for JavaScript clients. I still kept `DDhttp` for other clients like https://github.com/dd-center/DDatHome-go which I believe only pull once

**Comment by eight04** [comment]
If the Node client also pulls one task at one time (1 processor), the client won't make a bunch of HTTP requests at one time.

Since the wait time also increases when using multiple processors, it doesn't affect efficiency. Why do we use 48 processors?

**Comment by simon300000** [comment]
Interessanterweise I actually forgot why did I do so, I believe is because the delay of communication between server and client, for example if the client plan to execute task every 1 second, but the ping is like 400ms, and actually download takes 300ms, at end it will be more than 1 second.

**Comment by eight04** [comment]
The current code doesn't consider the delay either:
https://github.com/dd-center/DDatHome-nodejs/blob/f95c08f34c0ab410884689f676ac925c3db1b2b6/core.js#L59
The delay includes 1) the delay from the cluster server 2) the delay from the HTTP request.

----

If you want to keep the processing rate, a simpler implementation is to use a timer to pull tasks:
```js
setInterval(() => {
  ws.send("DDDhttp");
}, INTERVAL);

ws.on("message", message => {
  // process message
});
```
If you need some randomness, try [set-random-interval](https://www.npmjs.com/package/set-random-interval).

**Comment by simon300000** [comment]
In my mind the current code should consider delay since the the pause time `parallel*interval` should be bigger than delay, but with the new protocol `DDDhttp` this is not necessary anymore, now it is updated.
