### ISSUE TITLE
最近三天貌似没有任务

### ISSUE THREAD

**Issue by ouuan** [dd-center/Cluster-center#49]
最近三天我看了好几次都没有任务分配，弹幕里也有三人反馈，不知道是出了什么问题。

**Comment by simon300000** [comment]
bilibili 改了他们的什么东西，导致我这里有一个数据不能爬
我最近又有点忙，所以修的就很慢。。。

修复: https://github.com/dd-center/vtbs.moe/commit/a31a1a2c83bdc716c9992be3a6e0b7fdfdb8f1ce
